name: Prevent Stale Branches
on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  warn-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for stale branches
        run: |
          echo "🚨 WARNING: Branch other than 'main' detected!"
          echo "Current branch: ${{ github.ref_name }}"
          echo "Remember: Only 'main' branch should be used for production deployments"

          # List all branches
          git branch -r --format='%(refname:short)' | grep -v origin/main || true

          # Fail if this is a push to a non-main branch
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "❌ Non-main branch push detected. Consider merging to main instead."
            exit 1
          fi